version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - /workspaces/dotnet-signalr-rosetta-stone/config/appsettings.json:/app/config/appsettings.json
    extra_hosts:
    - "host.docker.internal:host-gateway"